import {
  Activity,
  Banknote,
  BarChart3,
  ClipboardCheck,
  Bell,
  Calendar,
  ClipboardList,
  Database,
  FileText,
  Flag,
  Files,
  FolderTree,
  Gamepad2,
  Globe,
  Home,
  History,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  Link2,
  Lock,
  LucideIcon,
  Megaphone,
  Menu,
  Monitor,
  Newspaper,
  ScrollText,
  Settings,
  ShoppingBag,
  Shield,
  SlidersHorizontal,
  SquareStack,
  TrendingUp,
  TriangleAlert,
  Users,
  Wallet,
  Wifi,
  Zap,
} from "lucide-react";

/**
 * Map backend icon string -> lucide component. Backend may send arbitrary
 * strings; unknown icons fall back to a sensible default.
 */
const map: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  home: Home,
  layout: LayoutGrid,
  layouts: LayoutGrid,
  database: Database,
  crud: Database,
  settings: Settings,
  pages: SquareStack,
  page: FileText,
  auth: Lock,
  authentication: Lock,
  lock: Lock,
  user: Users,
  users: Users,
  shop: ShoppingBag,
  shopping: ShoppingBag,
  playground: Gamepad2,
  support: LifeBuoy,
  // KOL / affiliate management
  shield: Shield,
  menu: Menu,
  newspaper: Newspaper,
  foldertree: FolderTree,
  activity: Activity,
  scrolltext: ScrollText,
  wifi: Wifi,
  megaphone: Megaphone,
  flag: Flag,
  globe: Globe,
  link: Link2,
  link2: Link2,
  wallet: Wallet,
  trend: TrendingUp,
  trendingup: TrendingUp,
  bar: BarChart3,
  barchart: BarChart3,
  monitor: Monitor,
  bell: Bell,
  calendar: Calendar,
  zap: Zap,
  clipboard: ClipboardList,
  clipboardlist: ClipboardList,
  clipboardcheck: ClipboardCheck,
  files: Files,
  banknote: Banknote,
  history: History,
  trianglealert: TriangleAlert,
  slidershorizontal: SlidersHorizontal,
  layoutdashboard: LayoutDashboard,
};

export function resolveIcon(name?: string): LucideIcon {
  if (!name) return SquareStack;
  const key = name.toLowerCase();
  return map[key] ?? SquareStack;
}
